### ISSUE TITLE
How to test the best fine-tune model

### ISSUE THREAD

**Issue by Mrbishuai** [Mark12Ding/FAME#1]
After the fine-tune model, I want to know where the test file is and how to operate it.

**Comment by Mark12Ding** [comment]
If I understand correctly, you are asking how to read the tenserboard logfile. Please refer to (https://www.tensorflow.org/tensorboard/). Also, if you want to validate the fine-tune model, you can use the 'resume' and 'evaluate' arguments in eval.py.
