### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by mertesdorfj** [Mark12Ding/FAME#3]
Hello,

thank you for publishing the FAME-code! It is of great interest for my research. However, I noticed your code is not licensed yet and unfortunately I need a license in order to use it for my masterthesis. Would it be possible to add a license for your code, e.g. the MIT-license (https://opensource.org/licenses/MIT) or Apache 2.0 license (https://www.apache.org/licenses/LICENSE-2.0)?

Thanks a lot in advance!

**Comment by Mark12Ding** [comment]
I have added the Apache 2.0 license. Good luck with your thesis :)

**Comment by mertesdorfj** [comment]
Thank you! :)
