### ISSUE TITLE
Could you please provide video retrieval evaluation code?

### ISSUE THREAD

**Issue by ZMHH-H** [Mark12Ding/FAME#6]
Hi! Thanks for your excellent work and open source your code!
Could you please provide video retrieval evaluation code?

**Comment by Mark12Ding** [comment]
Sure, I have uploaded the retrieval code at main_retrieve.py whereas it may exist some ad-hoc bugs. Please check it over before running it.

**Comment by ZMHH-H** [comment]
Thasnks!
